name: Flutter Release APK Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install Flutter with FVM
    - name: Install FVM
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$PWD/flutter/bin" >> $GITHUB_PATH  # Add Flutter to PATH temporarily
        export PATH="$PWD/flutter/bin:$PATH"  # Add Flutter to PATH for this script
        flutter pub global activate fvm
        fvm install 3.13.0  # Install Flutter version
        fvm use 3.13.0  # Use this version

    # Step 3: Add Flutter to PATH for all subsequent steps
    - name: Add FVM Flutter to PATH
      run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

    # Step 4: Check Flutter and Dart versions to verify correctness
    - name: Check Flutter and Dart versions
      run: |
        flutter --version
        dart --version

    # Step 5: Install dependencies
    - name: Install dependencies
      run: fvm flutter pub get

    # Step 6: Build release APK
    - name: Build release APK
      run: fvm flutter build apk --release --no-shrink

    # Step 7: Upload APK
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
