name: Flutter Release APK Build v2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Dart SDK version >=3.2.1
    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '>=3.2.1 <4.0.0'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Build release APK
      run: flutter build apk --release --no-shrink

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
